DROP DATABASE IF EXISTS cacheDB;
CREATE DATABASE cacheDB CHARACTER SET UTF8 COLLATE utf8_general_ci;
USE cacheDB;
CREATE TABLE dept
(
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	deptName VARCHAR(60)
);

CREATE TABLE emp
(
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(60),
	email VARCHAR(60),
	age BIGINT,
	sex BIGINT,
	dId BIGINT
);
