server:
  port: 8888
  
#debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cacheDB?useSSL=false&characterEncoding=utf8&useUnicode=true
    username: root
    password: 123456
  redis:  #redis配置
    host: 192.168.123.102
    port: 6379
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
logging:
  level:
    com.hobart.cache.mapper: debug
    